# Generated by Django 6.0.2 on 2026-02-27 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_automation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appcomponentpackage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_packages', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='appdevice',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_app_devices', to=settings.AUTH_USER_MODEL, verbose_name='锁定用户'),
        ),
        migrations.AddField(
            model_name='appelement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_elements', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='apppackage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_package_names', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='appproject',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='app_projects', to=settings.AUTH_USER_MODEL, verbose_name='团队成员'),
        ),
        migrations.AddField(
            model_name='appproject',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_app_projects', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='appelement',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='app_automation.appproject', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='appscheduledtask',
            name='app_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_tasks', to='app_automation.apppackage', verbose_name='应用包名'),
        ),
        migrations.AddField(
            model_name='appscheduledtask',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='appscheduledtask',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_tasks', to='app_automation.appdevice', verbose_name='执行设备'),
        ),
        migrations.AddField(
            model_name='appscheduledtask',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='app_automation.appproject', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='appnotificationlog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='app_automation.appscheduledtask', verbose_name='关联任务'),
        ),
        migrations.AddField(
            model_name='apptestcase',
            name='app_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='app_automation.apppackage', verbose_name='应用包名'),
        ),
        migrations.AddField(
            model_name='apptestcase',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_test_cases', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='apptestcase',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='app_automation.appproject', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='appscheduledtask',
            name='test_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_tasks', to='app_automation.apptestcase', verbose_name='测试用例'),
        ),
        migrations.AddField(
            model_name='apptestexecution',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='app_automation.appdevice', verbose_name='执行设备'),
        ),
        migrations.AddField(
            model_name='apptestexecution',
            name='test_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='app_automation.apptestcase', verbose_name='测试用例'),
        ),
        migrations.AddField(
            model_name='apptestexecution',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_test_executions', to=settings.AUTH_USER_MODEL, verbose_name='执行用户'),
        ),
        migrations.AddField(
            model_name='apptestsuite',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_test_suites', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='apptestsuite',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_suites', to='app_automation.appproject', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='apptestexecution',
            name='test_suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='app_automation.apptestsuite', verbose_name='所属套件'),
        ),
        migrations.AddField(
            model_name='appscheduledtask',
            name='test_suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_tasks', to='app_automation.apptestsuite', verbose_name='测试套件'),
        ),
        migrations.AddField(
            model_name='apptestsuitecase',
            name='test_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suite_memberships', to='app_automation.apptestcase', verbose_name='测试用例'),
        ),
        migrations.AddField(
            model_name='apptestsuitecase',
            name='test_suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suite_cases', to='app_automation.apptestsuite', verbose_name='测试套件'),
        ),
        migrations.AddField(
            model_name='apptestsuite',
            name='test_cases',
            field=models.ManyToManyField(blank=True, through='app_automation.AppTestSuiteCase', to='app_automation.apptestcase', verbose_name='测试用例'),
        ),
        migrations.AddIndex(
            model_name='appdevice',
            index=models.Index(fields=['status'], name='app_devices_status_9e09a1_idx'),
        ),
        migrations.AddIndex(
            model_name='appdevice',
            index=models.Index(fields=['device_id'], name='app_devices_device__1b1f25_idx'),
        ),
        migrations.AddIndex(
            model_name='apppackage',
            index=models.Index(fields=['package_name'], name='app_package_package_555fb1_idx'),
        ),
        migrations.AddIndex(
            model_name='apppackage',
            index=models.Index(fields=['name'], name='app_package_name_cecc0d_idx'),
        ),
        migrations.AddIndex(
            model_name='appelement',
            index=models.Index(fields=['element_type'], name='app_element_element_c563e9_idx'),
        ),
        migrations.AddIndex(
            model_name='appelement',
            index=models.Index(fields=['name'], name='app_element_name_0cb360_idx'),
        ),
        migrations.AddIndex(
            model_name='appelement',
            index=models.Index(fields=['is_active'], name='app_element_is_acti_772d00_idx'),
        ),
        migrations.AddIndex(
            model_name='appnotificationlog',
            index=models.Index(fields=['status'], name='app_notific_status_b1a744_idx'),
        ),
        migrations.AddIndex(
            model_name='appnotificationlog',
            index=models.Index(fields=['notification_type'], name='app_notific_notific_b8d115_idx'),
        ),
        migrations.AddIndex(
            model_name='appnotificationlog',
            index=models.Index(fields=['created_at'], name='app_notific_created_35637c_idx'),
        ),
        migrations.AddIndex(
            model_name='apptestexecution',
            index=models.Index(fields=['status'], name='app_test_ex_status_9ca315_idx'),
        ),
        migrations.AddIndex(
            model_name='apptestexecution',
            index=models.Index(fields=['-created_at'], name='app_test_ex_created_05ebca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='apptestsuitecase',
            unique_together={('test_suite', 'test_case')},
        ),
    ]
