# Generated by Django 6.0.2 on 2026-03-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_automation', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appnotificationlog',
            name='task',
        ),
        migrations.AddField(
            model_name='appnotificationlog',
            name='task_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='关联任务ID'),
        ),
        migrations.AlterField(
            model_name='appnotificationlog',
            name='error_message',
            field=models.TextField(blank=True, help_text='发送失败时的错误信息', null=True, verbose_name='错误信息'),
        ),
        migrations.AlterField(
            model_name='appnotificationlog',
            name='notification_content',
            field=models.TextField(help_text='发送的通知内容', verbose_name='通知内容'),
        ),
        migrations.AlterField(
            model_name='appnotificationlog',
            name='recipient_info',
            field=models.JSONField(help_text='接收通知的用户信息', verbose_name='收件人信息'),
        ),
        migrations.AlterField(
            model_name='appnotificationlog',
            name='response_info',
            field=models.JSONField(blank=True, default=dict, help_text='接收方返回的响应信息', null=True, verbose_name='响应信息'),
        ),
        migrations.AlterField(
            model_name='appnotificationlog',
            name='retry_count',
            field=models.IntegerField(default=0, help_text='已重试的次数', verbose_name='重试次数'),
        ),
        migrations.AlterField(
            model_name='appnotificationlog',
            name='task_name',
            field=models.CharField(help_text='相关任务的名称', max_length=200, verbose_name='任务名称'),
        ),
        migrations.AlterField(
            model_name='appnotificationlog',
            name='task_type',
            field=models.CharField(blank=True, help_text='发送通知时的任务类型', max_length=20, null=True, verbose_name='任务类型快照'),
        ),
        migrations.AlterField(
            model_name='appnotificationlog',
            name='webhook_bot_info',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Webhook机器人信息'),
        ),
        migrations.DeleteModel(
            name='AppScheduledTask',
        ),
    ]
