# Generated by Django 6.0.2 on 2026-03-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_automation', '0003_remove_appnotificationlog_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appproject',
            name='status',
            field=models.CharField(choices=[('not_started', '未开始'), ('active', '进行中'), ('paused', '暂停'), ('completed', '已完成'), ('archived', '已归档')], default='not_started', max_length=20, verbose_name='项目状态'),
        ),
    ]
