# Generated by Django 6.0.2 on 2026-03-19 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_automation', '0004_add_project_references'),
        ('unified_projects', '0004_projectmodule_ai_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appproject',
            name='unified_meta_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_project', to='unified_projects.metaproject', verbose_name='统一元项目'),
        ),
    ]
