# Generated by Django 6.0.2 on 2026-04-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_automation', '0007_apptestexecution_report_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptestexecution',
            name='report_status',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='报告生成状态'),
        ),
        migrations.AlterField(
            model_name='apptestexecution',
            name='report_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='报告URL'),
        ),
        migrations.AlterField(
            model_name='apptestexecution',
            name='result',
            field=models.CharField(blank=True, choices=[('passed', '通过'), ('failed', '失败'), ('skipped', '跳过'), ('partial_failed', '部分失败')], default=None, max_length=20, null=True, verbose_name='测试结果'),
        ),
    ]
