# Generated by Django 6.0.2 on 2026-04-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_automation', '0009_apptestexecution_skipped_steps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apptestconfig',
            name='ocr_engine',
            field=models.CharField(choices=[('tesseract', 'Tesseract OCR'), ('ppocr', 'PP-OCRv5')], default='tesseract', help_text='APP自动化测试使用的 OCR 引擎', max_length=20, verbose_name='OCR 引擎'),
        ),
        migrations.AddField(
            model_name='apptestconfig',
            name='ocr_language',
            field=models.CharField(default='chi_sim+eng', help_text='Tesseract: chi_sim(中文), eng(英文), chi_sim+eng(中英文)', max_length=20, verbose_name='OCR 语言'),
        ),
        migrations.AddField(
            model_name='apptestconfig',
            name='ocr_min_confidence',
            field=models.FloatField(default=0.3, help_text='低于此置信度的识别结果将被过滤', verbose_name='OCR 最小置信度'),
        ),
        migrations.AddField(
            model_name='apptestconfig',
            name='ocr_use_gpu',
            field=models.BooleanField(default=False, help_text='PP-OCRv5 可使用 GPU 加速', verbose_name='OCR 使用 GPU'),
        ),
    ]
