# Generated by Django 6.0.2 on 2026-04-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_automation', '0011_remove_ppocr_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='apppackage',
            name='apk_file',
            field=models.FileField(blank=True, help_text='上传的APK安装包（可选）', null=True, upload_to='app_automation/packages/', verbose_name='APK文件'),
        ),
    ]
