# Generated by Django 6.0.2 on 2026-04-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_automation', '0012_add_apk_file_to_app_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='apppackage',
            name='apk_filename',
            field=models.CharField(blank=True, default='', help_text='APK文件的唯一文件名', max_length=255, verbose_name='APK文件名'),
        ),
        migrations.AddField(
            model_name='apppackage',
            name='apk_filepath',
            field=models.CharField(blank=True, default='', help_text='APK文件的完整存储路径', max_length=500, verbose_name='APK文件路径'),
        ),
    ]
