# Generated by Django 6.0.2 on 2026-04-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_automation', '0013_add_apk_filepath_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='apppackage',
            name='remarks',
            field=models.CharField(blank=True, default='', help_text='最多30个字符，可选字段', max_length=30, verbose_name='备注'),
        ),
    ]
