# Generated by Codex on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_automation', '0014_add_remarks_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdevice',
            name='lock_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='锁定过期时间'),
        ),
        migrations.AddField(
            model_name='appdevice',
            name='lock_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近心跳时间'),
        ),
        migrations.AddField(
            model_name='appdevice',
            name='lock_session_id',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='锁定会话ID'),
        ),
        migrations.AddField(
            model_name='appdevice',
            name='lock_type',
            field=models.CharField(blank=True, choices=[('manual', '手动锁定'), ('remote_session', '远程会话'), ('automation', '自动化执行')], default='', max_length=32, verbose_name='锁定类型'),
        ),
        migrations.AddIndex(
            model_name='appdevice',
            index=models.Index(fields=['lock_type'], name='app_devices_lock_ty_773fd1_idx'),
        ),
        migrations.AddIndex(
            model_name='appdevice',
            index=models.Index(fields=['lock_expires_at'], name='app_devices_lock_ex_9cab11_idx'),
        ),
    ]
