# Generated by Django 6.0.2 on 2026-04-27 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_automation', '0015_appdevice_lock_session_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appdevice',
            new_name='app_devices_lock_ty_a52f01_idx',
            old_name='app_devices_lock_ty_773fd1_idx',
        ),
        migrations.RenameIndex(
            model_name='appdevice',
            new_name='app_devices_lock_ex_354d3e_idx',
            old_name='app_devices_lock_ex_9cab11_idx',
        ),
    ]
