# Generated by Django 6.0.2 on 2026-05-06 15:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("executions", "0002_initial"),
        ("projects", "0003_project_unified_meta_project_alter_project_status"),
        ("testcases", "0004_testcaseimportrecord_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeChangeAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_commit",
                    models.CharField(max_length=40, verbose_name="基准 Commit SHA"),
                ),
                (
                    "head_commit",
                    models.CharField(max_length=40, verbose_name="当前 Commit SHA"),
                ),
                (
                    "changed_files",
                    models.JSONField(blank=True, default=list, verbose_name="变更文件列表"),
                ),
                (
                    "changed_functions",
                    models.JSONField(blank=True, default=list, verbose_name="变更函数列表"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "排队中"),
                            ("running", "分析中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="异步任务ID"
                    ),
                ),
                ("progress", models.IntegerField(default=0, verbose_name="进度(%)")),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "代码变更分析",
                "verbose_name_plural": "代码变更分析",
                "db_table": "precision_change_analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImpactAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "impacted_functions",
                    models.JSONField(blank=True, default=list, verbose_name="受影响函数列表"),
                ),
                (
                    "impacted_testcases",
                    models.JSONField(
                        blank=True, default=list, verbose_name="受影响用例ID列表"
                    ),
                ),
                (
                    "min_regression_set",
                    models.JSONField(blank=True, default=list, verbose_name="最小回归集"),
                ),
                (
                    "regression_time_estimate",
                    models.IntegerField(default=0, verbose_name="预估回归时间(秒)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "计算中"), ("completed", "已完成")],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "change_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impact_results",
                        to="precision_testing.codechangeanalysis",
                        verbose_name="关联变更分析",
                    ),
                ),
            ],
            options={
                "verbose_name": "影响分析",
                "verbose_name_plural": "影响分析",
                "db_table": "precision_impact_analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrecisionRunRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_testcases",
                    models.JSONField(default=list, verbose_name="选中用例ID列表"),
                ),
                (
                    "total_testcases",
                    models.IntegerField(default=0, verbose_name="项目总用例数"),
                ),
                ("reduction_rate", models.FloatField(default=0.0, verbose_name="缩减率")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "排队中"),
                            ("running", "执行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="异步任务ID"
                    ),
                ),
                ("progress", models.IntegerField(default=0, verbose_name="进度(%)")),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "impact_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="precision_runs",
                        to="precision_testing.impactanalysis",
                        verbose_name="关联影响分析",
                    ),
                ),
                (
                    "run_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="precision_runs",
                        to="executions.testplan",
                        verbose_name="关联测试计划",
                    ),
                ),
            ],
            options={
                "verbose_name": "精准回归执行",
                "verbose_name_plural": "精准回归执行",
                "db_table": "precision_run_records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RepoBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repo_path", models.CharField(max_length=500, verbose_name="仓库本地路径")),
                (
                    "default_branch",
                    models.CharField(
                        default="main", max_length=100, verbose_name="默认分支"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repo_binding",
                        to="projects.project",
                        verbose_name="关联项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "仓库绑定",
                "verbose_name_plural": "仓库绑定",
                "db_table": "precision_repo_bindings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="codechangeanalysis",
            name="repo_binding",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analyses",
                to="precision_testing.repobinding",
                verbose_name="关联仓库",
            ),
        ),
        migrations.CreateModel(
            name="RiskPredictionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("risk_score", models.FloatField(verbose_name="风险分数")),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("critical", "极高"),
                        ],
                        default="low",
                        max_length=20,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "features",
                    models.JSONField(blank=True, default=dict, verbose_name="特征向量"),
                ),
                (
                    "model_version",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="模型版本"
                    ),
                ),
                (
                    "predicted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="预测时间"
                    ),
                ),
                (
                    "impact_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_records",
                        to="precision_testing.impactanalysis",
                        verbose_name="关联影响分析",
                    ),
                ),
                (
                    "testcase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_predictions",
                        to="testcases.testcase",
                        verbose_name="测试用例",
                    ),
                ),
            ],
            options={
                "verbose_name": "风险预测",
                "verbose_name_plural": "风险预测",
                "db_table": "precision_risk_predictions",
                "ordering": ["-predicted_at"],
            },
        ),
        migrations.CreateModel(
            name="TestCaseCodeMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "function_signature",
                    models.CharField(
                        help_text="格式: apps.module.views:ClassName.method_name",
                        max_length=500,
                        verbose_name="函数签名",
                    ),
                ),
                ("file_path", models.CharField(max_length=500, verbose_name="文件相对路径")),
                (
                    "mapping_type",
                    models.CharField(
                        choices=[
                            ("manual", "手工映射"),
                            ("auto_static", "静态分析"),
                            ("auto_dynamic", "动态学习"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="映射类型",
                    ),
                ),
                ("confidence", models.FloatField(default=1.0, verbose_name="置信度")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "testcase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_mappings",
                        to="testcases.testcase",
                        verbose_name="测试用例",
                    ),
                ),
            ],
            options={
                "verbose_name": "用例代码映射",
                "verbose_name_plural": "用例代码映射",
                "db_table": "precision_testcase_mappings",
                "ordering": ["-created_at"],
                "unique_together": {("testcase", "function_signature")},
            },
        ),
    ]
