# Generated by Django 6.0.2 on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('precision_testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repobinding',
            name='repo_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='仓库远程地址'),
        ),
    ]