# Generated by Django 5.2.14 on 2026-05-15 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('precision_testing', '0002_add_repo_url'),
    ]

    operations = [
    ]
