# Generated by Django 5.2.14 on 2026-05-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("precision_testing", "0003_add_repo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="precisionrunrecord",
            name="error_message",
            field=models.TextField(blank=True, verbose_name="错误信息"),
        ),
        migrations.AddField(
            model_name="repobinding",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="仓库显示名称"
            ),
        ),
        migrations.AlterField(
            model_name="repobinding",
            name="repo_path",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="仓库本地路径"
            ),
        ),
    ]
