# Generated by Django 5.2.14 on 2026-05-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "precision_testing",
            "0004_precisionrunrecord_error_message_repobinding_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="precisionrunrecord",
            name="supplement_testcases",
            field=models.JSONField(default=list, verbose_name="补充用例ID列表"),
        ),
    ]
