# Generated by Django 6.0.2 on 2026-03-23 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unified_projects', '0005_metaproject_unified_meta_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AICase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='用例名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('task_description', models.TextField(help_text='自然语言任务描述', verbose_name='任务描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_testing_created_cases', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': 'AI测试用例',
                'verbose_name_plural': 'AI测试用例',
                'db_table': 'ai_testing_cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AiProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_testing_projects', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('unified_meta_project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_module', to='unified_projects.metaproject', verbose_name='关联元项目')),
            ],
            options={
                'verbose_name': 'AI测试项目',
                'verbose_name_plural': 'AI测试项目',
                'db_table': 'ai_testing_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIExecutionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=200, verbose_name='用例名称快照')),
                ('task_description', models.TextField(blank=True, default='', help_text='用户输入的原始任务描述', verbose_name='任务描述')),
                ('execution_mode', models.CharField(choices=[('text', '文本模式')], default='text', max_length=20, verbose_name='执行模式')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('passed', '成功'), ('failed', '失败'), ('stopped', '已停止')], default='pending', max_length=20, verbose_name='执行状态')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='执行时长(秒)')),
                ('logs', models.TextField(blank=True, default='', verbose_name='执行日志')),
                ('steps_completed', models.JSONField(default=list, verbose_name='已完成步骤')),
                ('planned_tasks', models.JSONField(default=list, verbose_name='规划任务')),
                ('gif_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='GIF录制路径')),
                ('screenshots_sequence', models.JSONField(default=list, verbose_name='截图序列')),
                ('ai_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_testing.aicase', verbose_name='关联AI用例')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_testing_executions', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_testing.aiproject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'AI测试报告',
                'verbose_name_plural': 'AI测试报告',
                'db_table': 'ai_testing_execution_records',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddField(
            model_name='aicase',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_testing.aiproject', verbose_name='所属项目'),
        ),
    ]
