# Generated by Django 6.0.2 on 2026-03-23 14:47

from django.db import migrations
from django.db import connection

def migrate_and_fix_data(apps, schema_editor):
    """
    数据迁移与修复脚本
    1. 从旧表 ui_ai_cases 迁移数据到 ai_testing_cases
    2. 从旧表 ui_ai_execution_records 迁移数据到 ai_testing_execution_records
    3. 为没有 project 的旧数据分配一个默认项目
    """
    
    # 检查旧表是否存在
    with connection.cursor() as cursor:
        cursor.execute("SHOW TABLES LIKE 'ui_ai_cases'")
        ui_ai_cases_exists = cursor.fetchone()
        
        cursor.execute("SHOW TABLES LIKE 'ui_ai_execution_records'")
        ui_ai_execution_records_exists = cursor.fetchone()
        
        if ui_ai_cases_exists:
            print("开始迁移 AI 用例数据...")
            cursor.execute("""
                INSERT IGNORE INTO ai_testing_cases (id, name, description, task_description, created_at, updated_at, created_by_id, project_id)
                SELECT id, name, description, task_description, created_at, updated_at, created_by_id, NULL
                FROM ui_ai_cases;
            """)
            
        if ui_ai_execution_records_exists:
            print("开始迁移 AI 执行记录数据...")
            cursor.execute("""
                INSERT IGNORE INTO ai_testing_execution_records (
                    id, case_name, task_description, execution_mode, status, 
                    start_time, end_time, duration, logs, steps_completed, 
                    planned_tasks, executed_by_id, gif_path, screenshots_sequence, 
                    ai_case_id, project_id
                )
                SELECT 
                    id, case_name, task_description, execution_mode, status, 
                    start_time, end_time, duration, logs, steps_completed, 
                    planned_tasks, executed_by_id, gif_path, screenshots_sequence, 
                    ai_case_id, NULL
                FROM ui_ai_execution_records;
            """)

    # 获取需要的模型
    AiProject = apps.get_model('ai_testing', 'AiProject')
    AICase = apps.get_model('ai_testing', 'AICase')
    AIExecutionRecord = apps.get_model('ai_testing', 'AIExecutionRecord')
    from django.conf import settings
    user_app, user_model = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(user_app, user_model)

    # 查找所有项目为空的用例和记录
    orphan_cases = AICase.objects.filter(project__isnull=True)
    orphan_records = AIExecutionRecord.objects.filter(project__isnull=True)

    if orphan_cases.exists() or orphan_records.exists():
        # 获取或创建一个超级管理员用户作为默认创建者
        default_user = User.objects.filter(is_superuser=True).first()
        if not default_user:
            default_user = User.objects.first()

        if default_user:
            # 获取或创建一个默认的 AI 项目
            default_project, created = AiProject.objects.get_or_create(
                name="默认迁移项目",
                defaults={
                    "description": "存放历史迁移过来的未关联项目的数据",
                    "created_by": default_user
                }
            )

            # 修复没有关联项目的用例
            if orphan_cases.exists():
                for case in orphan_cases:
                    case.project = default_project
                    if not case.created_by:
                        case.created_by = default_user
                    case.save()

            # 修复没有关联项目的执行记录
            if orphan_records.exists():
                for record in orphan_records:
                    record.project = default_project
                    if not record.executed_by:
                        record.executed_by = default_user
                    record.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ai_testing', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_and_fix_data, reverse_code=migrations.RunPython.noop),
    ]

