# Generated by Django 6.0.2 on 2026-02-27 11:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='用例标题')),
                ('description', models.TextField(blank=True, verbose_name='用例描述')),
                ('preconditions', models.TextField(blank=True, verbose_name='前置条件')),
                ('steps', models.TextField(blank=True, max_length=1000, verbose_name='操作步骤')),
                ('expected_result', models.TextField(verbose_name='预期结果')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '紧急')], default='medium', max_length=20, verbose_name='优先级')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '激活'), ('deprecated', '废弃')], default='draft', max_length=20, verbose_name='状态')),
                ('test_type', models.CharField(choices=[('functional', '功能测试'), ('integration', '集成测试'), ('api', 'API测试'), ('ui', 'UI测试'), ('performance', '性能测试'), ('security', '安全测试')], default='functional', max_length=20, verbose_name='测试类型')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'db_table': 'testcases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCaseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='附件名称')),
                ('file', models.FileField(upload_to='testcase_attachments/', verbose_name='文件')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '测试用例附件',
                'verbose_name_plural': '测试用例附件',
                'db_table': 'testcase_attachments',
            },
        ),
        migrations.CreateModel(
            name='TestCaseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评论时间')),
            ],
            options={
                'verbose_name': '测试用例评论',
                'verbose_name_plural': '测试用例评论',
                'db_table': 'testcase_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCaseStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(verbose_name='步骤序号')),
                ('action', models.TextField(verbose_name='操作')),
                ('expected', models.TextField(verbose_name='预期结果')),
            ],
            options={
                'verbose_name': '测试用例步骤',
                'verbose_name_plural': '测试用例步骤',
                'db_table': 'testcase_steps',
                'ordering': ['step_number'],
            },
        ),
    ]
