# Generated by Django 6.0.2 on 2026-03-23 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_unified_meta_project_alter_project_status'),
        ('testcases', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseImportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名称')),
                ('status', models.CharField(choices=[('pending', '排队中'), ('running', '导入中'), ('success', '导入成功'), ('partial', '部分成功'), ('failed', '导入失败')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度(%)')),
                ('total_rows', models.IntegerField(default=0, verbose_name='总行数')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功数量')),
                ('failed_count', models.IntegerField(default=0, verbose_name='失败数量')),
                ('duplicate_count', models.IntegerField(default=0, verbose_name='重复数量')),
                ('error_summary', models.JSONField(blank=True, default=list, help_text='记录格式如 [{"row": 2, "error": "用例名称为空"}]', verbose_name='错误明细')),
                ('logs', models.TextField(blank=True, verbose_name='执行日志')),
                ('task_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='关联的异步任务ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_records', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '测试用例导入记录',
                'verbose_name_plural': '测试用例导入记录',
                'db_table': 'testcase_import_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
