# Generated by Django 6.0.2 on 2026-03-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0003_testcaseimportrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseimportrecord',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='testcase_imports/', verbose_name='文件'),
        ),
    ]
