# Generated by Django 6.0.2 on 2026-03-19 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        ('unified_projects', '0003_add_project_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='unified_meta_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='unified_projects.metaproject', verbose_name='统一元项目'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('not_started', '未开始'), ('active', '进行中'), ('paused', '暂停'), ('completed', '已完成'), ('archived', '已归档')], default='not_started', max_length=20, verbose_name='状态'),
        ),
    ]
