# Generated by Django 6.0.2 on 2026-02-27 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_testing', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiserviceconfig',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='apicollection',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api_testing.apicollection', verbose_name='父级集合'),
        ),
        migrations.AddField(
            model_name='apiproject',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='api_projects', to=settings.AUTH_USER_MODEL, verbose_name='团队成员'),
        ),
        migrations.AddField(
            model_name='apiproject',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_api_projects', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='apicollection',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='api_testing.apiproject', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='apirequest',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='api_testing.apicollection', verbose_name='所属集合'),
        ),
        migrations.AddField(
            model_name='apirequest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='environment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='environment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='api_testing.apiproject', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作用户'),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_testing.environment', verbose_name='使用环境'),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='executed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='执行者'),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='api_testing.apirequest', verbose_name='关联请求'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='api_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_testing.apirequest', verbose_name='API请求'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_testing.environment', verbose_name='执行环境'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_testing.scheduledtask', verbose_name='关联任务'),
        ),
        migrations.AddField(
            model_name='taskexecutionlog',
            name='executed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='执行者'),
        ),
        migrations.AddField(
            model_name='taskexecutionlog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='api_testing.scheduledtask', verbose_name='关联任务'),
        ),
        migrations.AddField(
            model_name='tasknotificationsetting',
            name='custom_recipients',
            field=models.ManyToManyField(blank=True, help_text='临时覆盖通知配置中的收件人设置', related_name='task_notification_settings_as_custom_recipient', to=settings.AUTH_USER_MODEL, verbose_name='自定义收件人'),
        ),
        migrations.AddField(
            model_name='tasknotificationsetting',
            name='notification_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_notification_settings', to='core.unifiednotificationconfig', verbose_name='通知配置'),
        ),
        migrations.AddField(
            model_name='tasknotificationsetting',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='api_testing.scheduledtask', verbose_name='关联任务'),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='executed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='执行者'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_test_suites', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_testing.environment', verbose_name='执行环境'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_suites', to='api_testing.apiproject', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='test_suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='api_testing.testsuite', verbose_name='测试套件'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='test_suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_testing.testsuite', verbose_name='测试套件'),
        ),
        migrations.AddField(
            model_name='testsuiterequest',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_testing.apirequest', verbose_name='API请求'),
        ),
        migrations.AddField(
            model_name='testsuiterequest',
            name='test_suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_testing.testsuite', verbose_name='测试套件'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='requests',
            field=models.ManyToManyField(through='api_testing.TestSuiteRequest', to='api_testing.apirequest', verbose_name='包含请求'),
        ),
        migrations.AddIndex(
            model_name='aiserviceconfig',
            index=models.Index(fields=['service_type', 'role'], name='api_ai_serv_service_7ca1bd_idx'),
        ),
        migrations.AddIndex(
            model_name='aiserviceconfig',
            index=models.Index(fields=['is_active'], name='api_ai_serv_is_acti_1b99e3_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['-created_at'], name='api_operati_created_f5f80f_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='api_operati_resourc_de446f_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['user', '-created_at'], name='api_operati_user_id_072297_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status'], name='api_notific_status_3bb8ea_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['notification_type'], name='api_notific_notific_6c611c_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['created_at'], name='api_notific_created_45cb75_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tasknotificationsetting',
            unique_together={('task',)},
        ),
        migrations.AlterUniqueTogether(
            name='testsuiterequest',
            unique_together={('test_suite', 'request')},
        ),
    ]
