# Generated by Django 6.0.2 on 2026-03-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_testing', '0006_apiproject_unified_meta_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequest',
            name='extractors',
            field=models.JSONField(blank=True, default=list, verbose_name='变量提取器'),
        ),
        migrations.AddField(
            model_name='testsuiterequest',
            name='extractors',
            field=models.JSONField(blank=True, default=list, verbose_name='变量提取器'),
        ),
    ]
