# Generated by Django 6.0.2 on 2026-03-30 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_testing', '0007_add_extractors_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterizedDataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='数据集名称')),
                ('data_type', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('json', 'JSON'), ('manual', '手动输入')], default='manual', max_length=20, verbose_name='数据类型')),
                ('file', models.FileField(blank=True, null=True, upload_to='api-testing/datasets/', verbose_name='数据文件')),
                ('data', models.JSONField(default=list, verbose_name='数据内容')),
                ('variables', models.JSONField(default=list, verbose_name='变量列名')),
                ('row_count', models.IntegerField(default=0, verbose_name='数据行数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='api_testing.apiproject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '参数化数据集',
                'verbose_name_plural': '参数化数据集',
                'db_table': 'api_parameterized_datasets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParameterizedExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RUNNING', '运行中'), ('COMPLETED', '已完成'), ('FAILED', '失败')], default='RUNNING', max_length=20, verbose_name='状态')),
                ('total_rows', models.IntegerField(default=0, verbose_name='总行数')),
                ('passed_rows', models.IntegerField(default=0, verbose_name='通过行数')),
                ('failed_rows', models.IntegerField(default=0, verbose_name='失败行数')),
                ('results', models.JSONField(default=list, verbose_name='执行结果')),
                ('start_time', models.DateTimeField(null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_testing.parameterizeddataset', verbose_name='数据集')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_testing.environment', verbose_name='环境')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='执行者')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_testing.apirequest', verbose_name='API请求')),
                ('test_suite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_testing.testsuite', verbose_name='测试套件')),
            ],
            options={
                'verbose_name': '参数化执行记录',
                'verbose_name_plural': '参数化执行记录',
                'db_table': 'api_parameterized_executions',
                'ordering': ['-created_at'],
            },
        ),
    ]
