# Generated by Django 6.0.2 on 2026-04-02 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_testing', '0009_testexecution_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexecution',
            name='single_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='api_testing.apirequest', verbose_name='单个请求'),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='test_suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='api_testing.testsuite', verbose_name='测试套件'),
        ),
    ]
