# Generated by Django 6.0.2 on 2026-04-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_testing', '0011_allow_null_execution_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexecution',
            name='report_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='报告URL'),
        ),
    ]
