# Generated by Django 6.0.2 on 2026-04-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_testing', '0012_testexecution_report_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequest',
            name='extract_variables',
            field=models.JSONField(default=list, verbose_name='变量提取规则'),
        ),
    ]
