# Generated by Django 6.0.2 on 2026-04-04 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_testing', '0014_testsuiterequset_add_extract_variables_skip_condition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testexecution',
            name='single_request',
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='executed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='执行者'),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='report_status',
            field=models.CharField(choices=[('PENDING', '待生成'), ('GENERATING', '生成中'), ('SUCCESS', '成功'), ('FAILED', '失败'), ('SKIPPED', '跳过')], default='PENDING', max_length=20, verbose_name='报告状态'),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='status',
            field=models.CharField(choices=[('PENDING', '待执行'), ('RUNNING', '执行中'), ('COMPLETED', '已完成'), ('FAILED', '执行失败'), ('CANCELLED', '已取消'), ('PARTIAL_FAILED', '部分失败')], default='PENDING', max_length=20, verbose_name='执行状态'),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='test_suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='api_testing.testsuite', verbose_name='测试套件'),
        ),
    ]
