# Generated by Django 6.0.2 on 2026-04-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_testing', '0015_remove_testexecution_single_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexecution',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='错误信息'),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='results',
            field=models.JSONField(default=list, verbose_name='执行结果'),
        ),
    ]
