# Generated by Django 6.0.2 on 2026-04-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_testing', '0016_add_error_message_to_testexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexecution',
            name='skipped_requests',
            field=models.IntegerField(default=0, verbose_name='跳过请求数'),
        ),
    ]
