# Generated by Django 6.0.2 on 2026-04-23 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentBuiltinDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.CharField(max_length=500, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('checksum', models.CharField(db_index=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent内置文档',
                'verbose_name_plural': 'Agent内置文档',
                'db_table': 'agent_builtin_documents',
            },
        ),
        migrations.CreateModel(
            name='AgentModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='配置名称')),
                ('provider', models.CharField(choices=[('openai_compatible', 'OpenAI Compatible'), ('custom', '自定义')], default='openai_compatible', max_length=32, verbose_name='提供商')),
                ('api_key', models.CharField(blank=True, max_length=500, null=True, verbose_name='API Key')),
                ('base_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Base URL')),
                ('model_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='模型名称')),
                ('max_tokens', models.IntegerField(default=2048, verbose_name='最大Token数')),
                ('temperature', models.FloatField(default=0.3, verbose_name='温度')),
                ('top_p', models.FloatField(default=0.9, verbose_name='Top P')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': 'Agent模型配置',
                'verbose_name_plural': 'Agent模型配置',
                'db_table': 'agent_model_configs',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default='', max_length=64, unique=True, verbose_name='会话ID')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='会话标题')),
                ('preset_code', models.CharField(default='general_qa', max_length=64, verbose_name='预设')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent会话',
                'verbose_name_plural': 'Agent会话',
                'db_table': 'agent_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', '助手'), ('system', '系统'), ('tool', '工具')], max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agent.agentsession')),
            ],
            options={
                'verbose_name': 'Agent消息',
                'verbose_name_plural': 'Agent消息',
                'db_table': 'agent_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset_code', models.CharField(default='general_qa', max_length=64)),
                ('tool_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20)),
                ('arguments', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assistant_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='agent.agentmessage')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='agent.agentsession')),
            ],
            options={
                'verbose_name': 'Agent工具调用',
                'verbose_name_plural': 'Agent工具调用',
                'db_table': 'agent_tool_calls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentBuiltinChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('token_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='agent.agentbuiltindocument')),
            ],
            options={
                'verbose_name': 'Agent内置文档分块',
                'verbose_name_plural': 'Agent内置文档分块',
                'db_table': 'agent_builtin_chunks',
                'ordering': ['document_id', 'chunk_index'],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
    ]
