# Generated by Django 6.0.2 on 2026-03-12 07:49

import apps.knowledge_base.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='知识库名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kb_knowledge_bases', to='projects.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '知识库',
                'verbose_name_plural': '知识库',
                'db_table': 'knowledge_bases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='knowledge_base.knowledgebase', verbose_name='所属知识库')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='knowledge_base.knowledgecategory', verbose_name='父级分类')),
            ],
            options={
                'verbose_name': '知识库分类',
                'verbose_name_plural': '知识库分类',
                'db_table': 'knowledge_categories',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='文档标题')),
                ('file', models.FileField(upload_to=apps.knowledge_base.models.knowledge_docs_upload_path, verbose_name='文档文件')),
                ('document_type', models.CharField(choices=[('pdf', 'PDF文档'), ('docx', 'Word文档'), ('doc', 'Word文档(旧版)'), ('txt', '文本文档'), ('md', 'Markdown文档')], max_length=10, verbose_name='文档类型')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('content', models.TextField(blank=True, verbose_name='文档内容(纯文本)')),
                ('description', models.TextField(blank=True, verbose_name='文档描述')),
                ('tags', models.JSONField(default=apps.knowledge_base.models.get_default_tags, verbose_name='标签列表')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='当前版本号')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='文件大小(bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='knowledge_base.knowledgecategory', verbose_name='所属分类')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='knowledge_base.knowledgebase', verbose_name='所属知识库')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kb_documents', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '知识库文档',
                'verbose_name_plural': '知识库文档',
                'db_table': 'knowledge_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='版本号')),
                ('file', models.FileField(upload_to=apps.knowledge_base.models.document_version_upload_path, verbose_name='版本文件快照')),
                ('content', models.TextField(blank=True, verbose_name='版本内容快照')),
                ('change_log', models.TextField(blank=True, verbose_name='变更说明')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='文件大小(bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='knowledge_base.knowledgedocument', verbose_name='关联文档')),
            ],
            options={
                'verbose_name': '文档版本',
                'verbose_name_plural': '文档版本',
                'db_table': 'document_versions',
                'ordering': ['-version_number'],
                'unique_together': {('document', 'version_number')},
            },
        ),
    ]
