# Generated by Django 6.0.2 on 2026-03-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        # KnowledgeBase 新增字段
        migrations.AddField(
            model_name='knowledgebase',
            name='chunk_size',
            field=models.PositiveIntegerField(default=500, help_text='文档分块时每个块的最大字符数', verbose_name='分块大小'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='chunk_overlap',
            field=models.PositiveIntegerField(default=50, help_text='文档分块时相邻块之间的重叠字符数', verbose_name='分块重叠'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='enable_vectorization',
            field=models.BooleanField(default=True, help_text='是否将文档内容向量化存储到向量数据库', verbose_name='是否向量化'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='vectorization_status',
            field=models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '处理失败')], default='pending', max_length=20, verbose_name='向量化状态'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='vectorization_error',
            field=models.TextField(blank=True, verbose_name='向量化错误信息'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='collection_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='向量集合名称'),
        ),
        # KnowledgeDocument 新增字段
        migrations.AddField(
            model_name='knowledgedocument',
            name='vector_status',
            field=models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '处理失败')], default='pending', max_length=20, verbose_name='向量化状态'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='vector_error',
            field=models.TextField(blank=True, verbose_name='向量化错误信息'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='chunk_count',
            field=models.PositiveIntegerField(default=0, verbose_name='分块数量'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='source',
            field=models.CharField(choices=[('upload', '后续上传'), ('initial', '创建时上传')], default='upload', max_length=20, verbose_name='文档来源'),
        ),
        # 修改 file 和 document_type 字段允许为空
        migrations.AlterField(
            model_name='knowledgedocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='knowledge_base/docs/', verbose_name='文档文件'),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='document_type',
            field=models.CharField(blank=True, choices=[('pdf', 'PDF文档'), ('docx', 'Word文档'), ('doc', 'Word文档(旧版)'), ('txt', '文本文档'), ('md', 'Markdown文档')], max_length=10, verbose_name='文档类型'),
        ),
    ]
