# Generated by Django 6.0.2 on 2026-03-12 14:01

import apps.knowledge_base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_add_vectorization_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgedocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.knowledge_base.models.knowledge_docs_upload_path, verbose_name='文档文件'),
        ),
    ]
