# Generated by Django 6.0.2 on 2026-03-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0003_alter_knowledgedocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='use_glm_direct',
            field=models.BooleanField(default=True, help_text='是否直接使用智谱GLM大模型解析整个文档（推荐），否则使用本地解析+图片识别', verbose_name='使用智谱GLM直接解析'),
        ),
    ]
