# Generated by Django 6.0.2 on 2026-03-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0004_add_use_glm_direct_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBaseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用该配置')),
                ('embedding_api_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='Embedding API Key')),
                ('embedding_base_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Embedding API Base URL')),
                ('embedding_model', models.CharField(default='text-embedding-v3', max_length=100, verbose_name='Embedding 模型名称')),
                ('refiner_api_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='Refiner API Key')),
                ('refiner_base_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Refiner API Base URL')),
                ('refiner_model', models.CharField(default='qwen-plus', max_length=100, verbose_name='Refiner 模型名称')),
                ('refiner_max_tokens', models.IntegerField(default=8192, verbose_name='Refiner 最大Token数')),
                ('refiner_temperature', models.FloatField(default=0.3, verbose_name='Refiner 温度参数')),
                ('zhipu_api_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='智谱 API Key')),
                ('zhipu_base_url', models.CharField(blank=True, default='https://open.bigmodel.cn/api/paas/v4', max_length=200, null=True, verbose_name='智谱 API Base URL')),
                ('zhipu_vision_model', models.CharField(default='glm-4v-flash', max_length=100, verbose_name='智谱视觉模型名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '知识库模型配置',
                'verbose_name_plural': '知识库模型配置',
                'db_table': 'knowledge_base_configs',
            },
        ),
    ]
