# Generated by Django 6.0.2 on 2026-03-29 12:07

from django.db import migrations, models


def migrate_zhipu_to_vision(apps, schema_editor):
    """将 zhipu_* 字段数据迁移到 vision_* 字段"""
    KnowledgeBaseConfig = apps.get_model('knowledge_base', 'KnowledgeBaseConfig')
    for config in KnowledgeBaseConfig.objects.all():
        config.vision_api_key = config.zhipu_api_key if hasattr(config, 'zhipu_api_key') else None
        config.vision_base_url = config.zhipu_base_url if hasattr(config, 'zhipu_base_url') else None
        config.vision_model = config.zhipu_vision_model if hasattr(config, 'zhipu_vision_model') else 'glm-4v-flash'
        config.vision_provider = 'zhipu'
        config.save(update_fields=['vision_api_key', 'vision_base_url', 'vision_model', 'vision_provider'])


def migrate_use_glm_to_vision(apps, schema_editor):
    """将 use_glm_direct 字段数据迁移到 use_vision_direct 字段"""
    KnowledgeBase = apps.get_model('knowledge_base', 'KnowledgeBase')
    for kb in KnowledgeBase.objects.all():
        kb.use_vision_direct = kb.use_glm_direct if hasattr(kb, 'use_glm_direct') else True
        kb.save(update_fields=['use_vision_direct'])


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0005_knowledgebaseconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebaseconfig',
            name='vision_api_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Vision API Key'),
        ),
        migrations.AddField(
            model_name='knowledgebaseconfig',
            name='vision_base_url',
            field=models.CharField(blank=True, help_text='留空则使用默认值，智谱: https://open.bigmodel.cn/api/paas/v4, OpenAI: https://api.openai.com/v1', max_length=200, null=True, verbose_name='Vision API Base URL'),
        ),
        migrations.AddField(
            model_name='knowledgebaseconfig',
            name='vision_model',
            field=models.CharField(default='glm-4v-flash', help_text='支持任意兼容 OpenAI 接口的视觉模型，如: gpt-4o, gpt-4-vision-preview, qwen-vl-max, glm-4v-flash 等', max_length=100, verbose_name='Vision 模型名称'),
        ),
        migrations.AddField(
            model_name='knowledgebaseconfig',
            name='vision_provider',
            field=models.CharField(choices=[('zhipu', '智谱 (使用文件解析API)'), ('openai', 'OpenAI兼容 (使用视觉模型逐页解析)')], default='zhipu', help_text='用于选择文档解析方式: zhipu 使用智谱文件解析API，openai 使用通用视觉模型逐页解析', max_length=20, verbose_name='Vision 服务商'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='use_vision_direct',
            field=models.BooleanField(default=True, help_text='是否直接使用视觉模型解析整个文档（推荐），否则使用本地解析+图片识别', verbose_name='使用视觉模型直接解析'),
        ),
        migrations.RunPython(migrate_zhipu_to_vision, migrations.RunPython.noop),
        migrations.RunPython(migrate_use_glm_to_vision, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='knowledgebaseconfig',
            name='zhipu_api_key',
        ),
        migrations.RemoveField(
            model_name='knowledgebaseconfig',
            name='zhipu_base_url',
        ),
        migrations.RemoveField(
            model_name='knowledgebaseconfig',
            name='zhipu_vision_model',
        ),
        migrations.RemoveField(
            model_name='knowledgebase',
            name='use_glm_direct',
        ),
    ]
