# Generated by Django 6.0.2

from django.db import migrations, models
import apps.knowledge_base.models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0006_rename_zhipu_to_vision'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebaseconfig',
            name='tika_server_url',
            field=models.CharField(default=apps.knowledge_base.models.get_default_tika_url, help_text='Apache Tika 文档解析服务地址', max_length=200, verbose_name='Tika Server URL'),
        ),
    ]