# Generated by Django 6.0.2 on 2026-04-27 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0007_add_tika_server_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgebaseconfig',
            name='vision_api_key',
        ),
        migrations.RemoveField(
            model_name='knowledgebaseconfig',
            name='vision_base_url',
        ),
        migrations.RemoveField(
            model_name='knowledgebaseconfig',
            name='vision_model',
        ),
        migrations.RemoveField(
            model_name='knowledgebaseconfig',
            name='vision_provider',
        ),
    ]
