# Generated by Django 6.0.2 on 2026-02-27 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiednotificationconfig',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddIndex(
            model_name='unifiednotificationconfig',
            index=models.Index(fields=['config_type'], name='unified_not_config__ff7bfc_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiednotificationconfig',
            index=models.Index(fields=['is_default'], name='unified_not_is_defa_2f6e9a_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiednotificationconfig',
            index=models.Index(fields=['is_active'], name='unified_not_is_acti_5d6fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiednotificationconfig',
            index=models.Index(fields=['created_by'], name='unified_not_created_a454b7_idx'),
        ),
    ]
