# Generated by Django 6.0.2 on 2026-03-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_performancestatistics_notificationtemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiednotificationconfig',
            name='config_type',
            field=models.CharField(choices=[('webhook_feishu', '飞书机器人'), ('webhook_wechat', '企业微信机器人'), ('webhook_dingtalk', '钉钉机器人'), ('webhook_generic', '通用Webhook')], default='webhook_feishu', max_length=20, verbose_name='配置类型'),
        ),
    ]
