# Generated by Django 6.0.2 on 2026-03-06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_unifiednotificationconfig_config_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='subject',
            field=models.CharField(blank=True, max_length=200, verbose_name='邮件主题'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='template_type',
            field=models.CharField(choices=[('markdown', 'Markdown'), ('html', 'HTML'), ('text', '纯文本')], default='markdown', max_length=20, verbose_name='模板类型'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='variables',
            field=models.JSONField(blank=True, default=list, verbose_name='模板变量'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='description',
            field=models.TextField(blank=True, verbose_name='模板描述'),
        ),
        migrations.AddField(
            model_name='unifiednotificationconfig',
            name='webhook_url',
            field=models.URLField(default='', max_length=500, verbose_name='Webhook URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unifiednotificationconfig',
            name='secret',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='签名密钥'),
        ),
        migrations.AddField(
            model_name='unifiednotificationconfig',
            name='business_types',
            field=models.JSONField(blank=True, default=list, verbose_name='业务类型'),
        ),
        migrations.AddField(
            model_name='unifiednotificationconfig',
            name='enable_ui_automation',
            field=models.BooleanField(default=True, verbose_name='启用UI自动化测试通知'),
        ),
        migrations.AddField(
            model_name='unifiednotificationconfig',
            name='enable_api_testing',
            field=models.BooleanField(default=True, verbose_name='启用接口测试通知'),
        ),
        migrations.AddField(
            model_name='unifiednotificationconfig',
            name='enable_app_automation',
            field=models.BooleanField(default=True, verbose_name='启用APP自动化测试通知'),
        ),
        migrations.AddField(
            model_name='unifiednotificationconfig',
            name='notification_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_configs', to='core.notificationtemplate', verbose_name='通知模板'),
        ),
        migrations.AlterField(
            model_name='unifiednotificationconfig',
            name='name',
            field=models.CharField(help_text='用于标识该机器人的名称', max_length=100, verbose_name='机器人名称'),
        ),
        migrations.AlterModelOptions(
            name='unifiednotificationconfig',
            options={'ordering': ['-created_at'], 'verbose_name': '通知配置', 'verbose_name_plural': '通知配置'},
        ),
        migrations.RemoveField(
            model_name='unifiednotificationconfig',
            name='webhook_bots',
        ),
    ]
