# Generated by Django 5.1.4 on 2026-03-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_email_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiednotificationconfig',
            name='email_attach_report',
            field=models.BooleanField(default=False, help_text='启用后邮件将附带HTML格式的测试报告附件', verbose_name='邮件附带测试报告'),
        ),
    ]
