# Generated by Django 6.0.2 on 2026-03-19 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_email_attach_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='content',
            field=models.TextField(help_text='支持变量替换，使用{{变量名}}格式', verbose_name='模板内容'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='是否默认模板'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='模板名称'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='subject',
            field=models.CharField(blank=True, help_text='邮件通知时使用的主题', max_length=200, verbose_name='邮件主题'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='variables',
            field=models.JSONField(blank=True, default=list, help_text='模板中使用的变量列表', verbose_name='模板变量'),
        ),
        migrations.AlterField(
            model_name='unifiednotificationconfig',
            name='business_types',
            field=models.JSONField(blank=True, default=list, help_text='适用的业务类型列表', verbose_name='业务类型'),
        ),
        migrations.AlterField(
            model_name='unifiednotificationconfig',
            name='notification_template',
            field=models.ForeignKey(blank=True, help_text='选择通知模板，用于发送通知时使用', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_configs', to='core.notificationtemplate', verbose_name='通知模板'),
        ),
        migrations.AlterField(
            model_name='unifiednotificationconfig',
            name='secret',
            field=models.CharField(blank=True, default='', help_text='钉钉机器人签名密钥（可选）', max_length=200, verbose_name='签名密钥'),
        ),
    ]
