# Generated by Django 6.0.2 on 2026-02-27 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        ('testcases', '0002_initial'),
        ('testsuites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testsuites', to='projects.project'),
        ),
        migrations.AddField(
            model_name='testsuitecase',
            name='testcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcases.testcase'),
        ),
        migrations.AddField(
            model_name='testsuitecase',
            name='testsuite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsuites.testsuite'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='testcases',
            field=models.ManyToManyField(through='testsuites.TestSuiteCase', to='testcases.testcase', verbose_name='测试用例'),
        ),
        migrations.AlterUniqueTogether(
            name='testsuitecase',
            unique_together={('testsuite', 'testcase')},
        ),
    ]
