# Generated by Django 6.0.2 on 2026-03-04 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_q', '0018_task_success_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('API', 'API测试'), ('UI', 'UI自动化'), ('APP', 'APP自动化')], max_length=20, verbose_name='所属模块')),
                ('task_type', models.CharField(choices=[('API_TEST_SUITE', 'API测试套件'), ('API_REQUEST', 'API请求'), ('UI_TEST_SUITE', 'UI测试套件'), ('UI_TEST_CASE', 'UI测试用例'), ('APP_TEST_SUITE', 'APP测试套件'), ('APP_TEST_CASE', 'APP测试用例')], max_length=30, verbose_name='任务类型')),
                ('project_id', models.IntegerField(blank=True, null=True, verbose_name='项目ID')),
                ('target_id', models.IntegerField(blank=True, null=True, verbose_name='目标ID')),
                ('environment_id', models.IntegerField(blank=True, null=True, verbose_name='环境ID')),
                ('task_config', models.JSONField(blank=True, default=dict, help_text='存储引擎、浏览器、设备、测试用例列表等配置', verbose_name='执行配置')),
                ('status', models.CharField(choices=[('ACTIVE', '激活'), ('PAUSED', '暂停'), ('COMPLETED', '已完成'), ('FAILED', '失败')], default='ACTIVE', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, default='', verbose_name='任务描述')),
                ('notify_on_success', models.BooleanField(default=False, verbose_name='成功时通知')),
                ('notify_on_failure', models.BooleanField(default=True, verbose_name='失败时通知')),
                ('notify_emails', models.JSONField(blank=True, default=list, verbose_name='通知邮箱')),
                ('use_webhook', models.BooleanField(default=False, verbose_name='使用Webhook通知')),
                ('webhook_url', models.URLField(blank=True, default='', verbose_name='Webhook地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='django_q.schedule', verbose_name='关联调度')),
            ],
            options={
                'verbose_name': '任务配置',
                'verbose_name_plural': '任务配置',
                'db_table': 'scheduler_schedule_config',
                'ordering': ['-created_at'],
            },
        ),
    ]
