# Generated by Django 6.0.2 on 2026-03-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleconfig',
            name='failure_count',
            field=models.IntegerField(default=0, verbose_name='失败次数'),
        ),
        migrations.AddField(
            model_name='scheduleconfig',
            name='last_run_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次运行时间'),
        ),
        migrations.AddField(
            model_name='scheduleconfig',
            name='success_count',
            field=models.IntegerField(default=0, verbose_name='成功次数'),
        ),
    ]
