# Generated by Django 6.0.2 on 2026-03-05 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_performancestatistics_notificationtemplate_and_more'),
        ('scheduler', '0004_scheduleconfig_failure_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleconfig',
            name='notification_template',
            field=models.ForeignKey(blank=True, help_text='选择通知模板，用于发送通知时使用', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_configs', to='core.notificationtemplate', verbose_name='通知模板'),
        ),
    ]
