# Generated by Django 5.1.4 on 2026-03-07 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_scheduleconfig_notification_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleconfig',
            name='notification_config',
            field=models.ForeignKey(blank=True, help_text='选择通知配置，用于发送通知时使用', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='core.unifiednotificationconfig', verbose_name='通知配置'),
        ),
    ]
