# Generated by Django 6.0.2 on 2026-02-27 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('ui_automation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aicase',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='aiexecutionrecord',
            name='ai_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ui_automation.aicase', verbose_name='关联AI用例'),
        ),
        migrations.AddField(
            model_name='aiexecutionrecord',
            name='executed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='执行人'),
        ),
        migrations.AddField(
            model_name='element',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='element',
            name='parent_element',
            field=models.ForeignKey(blank=True, help_text='用于构建元素层次结构', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ui_automation.element', verbose_name='父元素'),
        ),
        migrations.AddField(
            model_name='elementgroup',
            name='parent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ui_automation.elementgroup', verbose_name='父分组'),
        ),
        migrations.AddField(
            model_name='element',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elements', to='ui_automation.elementgroup', verbose_name='所属分组'),
        ),
        migrations.AddField(
            model_name='element',
            name='locator_strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ui_automation.locatorstrategy', verbose_name='定位策略'),
        ),
        migrations.AddField(
            model_name='operationrecord',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作用户'),
        ),
        migrations.AddField(
            model_name='pageobject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='pageobjectelement',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui_automation.element', verbose_name='元素'),
        ),
        migrations.AddField(
            model_name='pageobjectelement',
            name='page_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_object_elements', to='ui_automation.pageobject', verbose_name='页面对象'),
        ),
        migrations.AddField(
            model_name='scriptelementusage',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_usages', to='ui_automation.element', verbose_name='元素'),
        ),
        migrations.AddField(
            model_name='scriptstep',
            name='page_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ui_automation.pageobject', verbose_name='页面对象'),
        ),
        migrations.AddField(
            model_name='scriptstep',
            name='target_element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ui_automation.element', verbose_name='目标元素'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_test_cases', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='testcaseexecution',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case_executions', to=settings.AUTH_USER_MODEL, verbose_name='执行人'),
        ),
        migrations.AddField(
            model_name='testcaseexecution',
            name='test_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='ui_automation.testcase', verbose_name='测试用例'),
        ),
        migrations.AddField(
            model_name='testcasestep',
            name='element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ui_automation.element', verbose_name='目标元素'),
        ),
        migrations.AddField(
            model_name='testcasestep',
            name='test_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='ui_automation.testcase', verbose_name='测试用例'),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ui_test_executions', to=settings.AUTH_USER_MODEL, verbose_name='执行人员'),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='ui_automation.testexecution', verbose_name='测试执行'),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='test_script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='ui_automation.testscript', verbose_name='测试脚本'),
        ),
        migrations.AddField(
            model_name='scriptstep',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='ui_automation.testscript', verbose_name='所属脚本'),
        ),
        migrations.AddField(
            model_name='scriptelementusage',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_usages', to='ui_automation.testscript', verbose_name='脚本'),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='test_suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='ui_automation.testsuite', verbose_name='测试套件'),
        ),
        migrations.AddField(
            model_name='testcaseexecution',
            name='test_suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_executions', to='ui_automation.testsuite', verbose_name='所属测试套件'),
        ),
        migrations.AddField(
            model_name='testsuitescript',
            name='test_script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui_automation.testscript', verbose_name='测试脚本'),
        ),
        migrations.AddField(
            model_name='testsuitescript',
            name='test_suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suite_scripts', to='ui_automation.testsuite', verbose_name='测试套件'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='scripts',
            field=models.ManyToManyField(through='ui_automation.TestSuiteScript', to='ui_automation.testscript', verbose_name='测试脚本'),
        ),
        migrations.AddField(
            model_name='testsuitetestcase',
            name='test_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui_automation.testcase', verbose_name='测试用例'),
        ),
        migrations.AddField(
            model_name='testsuitetestcase',
            name='test_suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suite_test_cases', to='ui_automation.testsuite', verbose_name='测试套件'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='test_cases',
            field=models.ManyToManyField(blank=True, through='ui_automation.TestSuiteTestCase', to='ui_automation.testcase', verbose_name='测试用例'),
        ),
        migrations.AddField(
            model_name='uiproject',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='ui_projects', to=settings.AUTH_USER_MODEL, verbose_name='团队成员'),
        ),
        migrations.AddField(
            model_name='uiproject',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_ui_projects', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_suites', to='ui_automation.uiproject', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='testscript',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_scripts', to='ui_automation.uiproject', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='ui_automation.uiproject', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='testcaseexecution',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case_executions', to='ui_automation.uiproject', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='ui_automation.uiproject', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='pageobject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_objects', to='ui_automation.uiproject', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='elementgroup',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_groups', to='ui_automation.uiproject', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='element',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='ui_automation.uiproject', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='aiexecutionrecord',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ui_automation.uiproject', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='aicase',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ui_automation.uiproject', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='uischeduledtask',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='uischeduledtask',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui_automation.uiproject', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='uischeduledtask',
            name='test_suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ui_automation.testsuite', verbose_name='测试套件'),
        ),
        migrations.AddField(
            model_name='uinotificationlog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ui_automation.uischeduledtask', verbose_name='关联任务'),
        ),
        migrations.AddField(
            model_name='uitasknotificationsetting',
            name='custom_recipients',
            field=models.ManyToManyField(blank=True, help_text='临时覆盖通知配置中的收件人设置', related_name='ui_task_notification_settings_as_custom_recipient', to=settings.AUTH_USER_MODEL, verbose_name='自定义收件人'),
        ),
        migrations.AddField(
            model_name='uitasknotificationsetting',
            name='notification_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ui_task_notification_settings', to='core.unifiednotificationconfig', verbose_name='通知配置'),
        ),
        migrations.AddField(
            model_name='uitasknotificationsetting',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='ui_automation.uischeduledtask', verbose_name='关联任务'),
        ),
        migrations.AddIndex(
            model_name='operationrecord',
            index=models.Index(fields=['-created_at'], name='ui_operatio_created_735396_idx'),
        ),
        migrations.AddIndex(
            model_name='operationrecord',
            index=models.Index(fields=['resource_type', 'resource_id'], name='ui_operatio_resourc_cb1b52_idx'),
        ),
        migrations.AddIndex(
            model_name='operationrecord',
            index=models.Index(fields=['user', '-created_at'], name='ui_operatio_user_id_1217fc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pageobjectelement',
            unique_together={('page_object', 'method_name')},
        ),
        migrations.AlterUniqueTogether(
            name='testcasestep',
            unique_together={('test_case', 'step_number')},
        ),
        migrations.AlterUniqueTogether(
            name='scriptstep',
            unique_together={('script', 'step_order')},
        ),
        migrations.AlterUniqueTogether(
            name='scriptelementusage',
            unique_together={('script', 'element', 'line_number')},
        ),
        migrations.AlterUniqueTogether(
            name='testsuitetestcase',
            unique_together={('test_suite', 'test_case')},
        ),
        migrations.AlterUniqueTogether(
            name='pageobject',
            unique_together={('project', 'name')},
        ),
        migrations.AddIndex(
            model_name='element',
            index=models.Index(fields=['project', 'page'], name='ui_elements_project_26e1bb_idx'),
        ),
        migrations.AddIndex(
            model_name='element',
            index=models.Index(fields=['project', 'element_type'], name='ui_elements_project_1fb22d_idx'),
        ),
        migrations.AddIndex(
            model_name='element',
            index=models.Index(fields=['validation_status'], name='ui_elements_validat_479f58_idx'),
        ),
        migrations.AddIndex(
            model_name='uinotificationlog',
            index=models.Index(fields=['status'], name='ui_notifica_status_2f9a84_idx'),
        ),
        migrations.AddIndex(
            model_name='uinotificationlog',
            index=models.Index(fields=['notification_type'], name='ui_notifica_notific_8889ee_idx'),
        ),
        migrations.AddIndex(
            model_name='uinotificationlog',
            index=models.Index(fields=['created_at'], name='ui_notifica_created_6577cc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='uitasknotificationsetting',
            unique_together={('task',)},
        ),
    ]
