# Generated by Django 6.0.2 on 2026-03-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0004_add_task_id_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'ordering': ['page', 'order', 'name'], 'verbose_name': 'UI元素', 'verbose_name_plural': 'UI元素'},
        ),
        migrations.AddField(
            model_name='element',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='aiexecutionrecord',
            name='status',
            field=models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('passed', '成功'), ('failed', '失败'), ('stopped', '已停止')], default='pending', max_length=20, verbose_name='执行状态'),
        ),
    ]
