# Generated by Django 6.0.2 on 2026-03-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0005_alter_element_options_element_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcasestep',
            name='assert_type',
            field=models.CharField(blank=True, choices=[('textContains', '文本包含'), ('textEquals', '文本等于'), ('isVisible', '元素可见'), ('exists', '元素存在'), ('hasAttribute', '属性值'), ('urlContains', 'URL包含')], max_length=20, verbose_name='断言类型'),
        ),
    ]
