# Generated by Django 6.0.2 on 2026-03-24 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0008_uiproject_unified_meta_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiexecutionrecord',
            name='ai_case',
        ),
        migrations.RemoveField(
            model_name='aiexecutionrecord',
            name='executed_by',
        ),
        migrations.RemoveField(
            model_name='aiexecutionrecord',
            name='project',
        ),
        migrations.DeleteModel(
            name='AICase',
        ),
        migrations.DeleteModel(
            name='AIExecutionRecord',
        ),
    ]
