# Generated by Django 6.0.2 on 2026-04-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0011_testexecution_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testexecution',
            name='report_status',
            field=models.CharField(choices=[('PENDING', '待生成'), ('GENERATING', '生成中'), ('SUCCESS', '成功'), ('FAILED', '失败'), ('SKIPPED', '跳过')], default='PENDING', max_length=20, verbose_name='报告状态'),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='status',
            field=models.CharField(choices=[('PENDING', '待执行'), ('RUNNING', '运行中'), ('SUCCESS', '成功'), ('FAILED', '失败'), ('ABORTED', '中止'), ('PARTIAL_FAILED', '部分失败')], default='PENDING', max_length=20, verbose_name='执行状态'),
        ),
    ]
