# Generated by Django 6.0.2 on 2026-02-27 11:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='计划名称')),
                ('description', models.TextField(blank=True, verbose_name='计划描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '测试计划',
                'verbose_name_plural': '测试计划',
                'db_table': 'test_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='执行名称')),
                ('description', models.TextField(blank=True, verbose_name='执行描述')),
                ('status', models.CharField(choices=[('untested', '未测试'), ('in_progress', '进行中'), ('completed', '已完成'), ('blocked', '阻塞')], default='untested', max_length=20, verbose_name='状态')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='截止日期')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '测试执行',
                'verbose_name_plural': '测试执行',
                'db_table': 'test_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestRunCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('untested', '未测试'), ('passed', '通过'), ('failed', '失败'), ('blocked', '阻塞'), ('retest', '重测')], default='untested', max_length=20, verbose_name='执行状态')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '紧急')], default='medium', max_length=20, verbose_name='优先级')),
                ('actual_result', models.TextField(blank=True, verbose_name='实际结果')),
                ('comments', models.TextField(blank=True, verbose_name='备注')),
                ('defects', models.JSONField(default=list, verbose_name='关联缺陷')),
                ('elapsed_time', models.DurationField(blank=True, null=True, verbose_name='执行耗时')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '测试执行用例',
                'verbose_name_plural': '测试执行用例',
                'db_table': 'test_run_cases',
                'ordering': ['testcase__id'],
            },
        ),
        migrations.CreateModel(
            name='TestRunCaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('untested', '未测试'), ('passed', '通过'), ('failed', '失败'), ('blocked', '阻塞'), ('retest', '重测')], max_length=20, verbose_name='执行状态')),
                ('actual_result', models.TextField(blank=True, verbose_name='实际结果')),
                ('comments', models.TextField(blank=True, verbose_name='备注')),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='执行时间')),
            ],
            options={
                'verbose_name': '测试执行历史',
                'verbose_name_plural': '测试执行历史',
                'db_table': 'test_run_case_history',
                'ordering': ['-executed_at'],
            },
        ),
    ]
