# Generated by Django 6.0.2 on 2026-02-27 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('executions', '0001_initial'),
        ('projects', '0001_initial'),
        ('testcases', '0001_initial'),
        ('versions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testplan',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assigned_plans', to=settings.AUTH_USER_MODEL, verbose_name='指派给'),
        ),
        migrations.AddField(
            model_name='testplan',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_plans', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='testplan',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='test_plans', to='projects.project', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='testplan',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_plans', to='versions.version', verbose_name='关联版本'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_runs', to=settings.AUTH_USER_MODEL, verbose_name='执行人'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_runs', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='projects.project', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='test_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='executions.testplan', verbose_name='测试计划'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='versions.version', verbose_name='关联版本'),
        ),
        migrations.AddField(
            model_name='testruncase',
            name='executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='执行者'),
        ),
        migrations.AddField(
            model_name='testruncase',
            name='test_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_cases', to='executions.testrun', verbose_name='测试执行'),
        ),
        migrations.AddField(
            model_name='testruncase',
            name='testcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcases.testcase', verbose_name='测试用例'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='testcases',
            field=models.ManyToManyField(related_name='test_runs', through='executions.TestRunCase', to='testcases.testcase', verbose_name='测试用例'),
        ),
        migrations.AddField(
            model_name='testruncasehistory',
            name='executed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='执行者'),
        ),
        migrations.AddField(
            model_name='testruncasehistory',
            name='run_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='executions.testruncase', verbose_name='执行用例'),
        ),
        migrations.AlterUniqueTogether(
            name='testruncase',
            unique_together={('test_run', 'testcase')},
        ),
    ]
