# Generated by Django 6.0.2 on 2026-03-19 05:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('status', models.CharField(choices=[('active', '进行中'), ('paused', '暂停'), ('completed', '已完成'), ('archived', '已归档')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_projects', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '元项目',
                'verbose_name_plural': '元项目',
                'db_table': 'unified_meta_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetaProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', '负责人'), ('admin', '管理员'), ('developer', '开发者'), ('tester', '测试者'), ('viewer', '观察者')], default='tester', max_length=20, verbose_name='角色')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='加入时间')),
                ('meta_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='unified_projects.metaproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '元项目成员',
                'verbose_name_plural': '元项目成员',
                'db_table': 'unified_meta_project_members',
                'unique_together': {('meta_project', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ProjectModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(choices=[('API', 'API测试'), ('UI', 'UI自动化'), ('APP', 'APP自动化')], max_length=10, verbose_name='模块类型')),
                ('config', models.JSONField(default=dict, verbose_name='模块配置')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('meta_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='unified_projects.metaproject', verbose_name='所属元项目')),
            ],
            options={
                'verbose_name': '项目模块',
                'verbose_name_plural': '项目模块',
                'db_table': 'unified_project_modules',
                'unique_together': {('meta_project', 'module_type')},
            },
        ),
    ]
