# Generated by Django 6.0.2 on 2026-03-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified_projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metaproject',
            name='status',
            field=models.CharField(choices=[('active', '进行中'), ('paused', '暂停'), ('completed', '已完成'), ('archived', '已归档')], default='not_started', max_length=20, verbose_name='状态'),
        ),
    ]
