# Generated by Django 6.0.2 on 2026-03-19 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_testing', '0005_add_project_references'),
        ('app_automation', '0004_add_project_references'),
        ('ui_automation', '0007_add_project_references'),
        ('unified_projects', '0002_alter_metaproject_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodule',
            name='api_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_module', to='api_testing.apiproject', verbose_name='API项目'),
        ),
        migrations.AddField(
            model_name='projectmodule',
            name='app_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_module', to='app_automation.appproject', verbose_name='APP项目'),
        ),
        migrations.AddField(
            model_name='projectmodule',
            name='ui_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_module', to='ui_automation.uiproject', verbose_name='UI项目'),
        ),
        migrations.AlterField(
            model_name='metaproject',
            name='status',
            field=models.CharField(choices=[('not_started', '未开始'), ('active', '进行中'), ('paused', '暂停'), ('completed', '已完成'), ('archived', '已归档')], default='not_started', max_length=20, verbose_name='状态'),
        ),
    ]
