# Generated by Django 6.0.2 on 2026-03-19 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_unified_meta_project_alter_project_status'),
        ('unified_projects', '0003_add_project_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodule',
            name='ai_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_module', to='projects.project', verbose_name='AI项目'),
        ),
        migrations.AlterField(
            model_name='projectmodule',
            name='module_type',
            field=models.CharField(choices=[('AI', 'AI用例生成'), ('API', 'API测试'), ('UI', 'UI自动化'), ('APP', 'APP自动化')], max_length=10, verbose_name='模块类型'),
        ),
    ]
