# Generated by Django 6.0.2 on 2026-03-19 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified_projects', '0004_projectmodule_ai_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaproject',
            name='unified_meta_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_projects', to='unified_projects.metaproject', verbose_name='父项目'),
        ),
    ]
