# Generated by Django 6.0.2 on 2026-03-23 14:05

import django.db.models.deletion
from django.db import migrations, models


def clear_old_ai_project_links(apps, schema_editor):
    """
    在修改外键类型之前，清空旧的 ai_project 数据。
    因为外键表发生了变更 (从 projects_project 变为了 ai_testing_projects)，
    如果旧数据里存了老的项目ID，会导致添加外键约束时失败 (MySQL Error 1452)。
    """
    ProjectModule = apps.get_model('unified_projects', 'ProjectModule')
    ProjectModule.objects.update(ai_project=None)


class Migration(migrations.Migration):

    dependencies = [
        ('ai_testing', '0001_initial'),
        ('unified_projects', '0005_metaproject_unified_meta_project'),
    ]

    operations = [
        migrations.RunPython(clear_old_ai_project_links, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='projectmodule',
            name='ai_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_config', to='ai_testing.aiproject', verbose_name='AI项目'),
        ),
    ]
