# Generated by Django 6.0.2 on 2026-03-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified_projects', '0006_alter_projectmodule_ai_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodule',
            name='module_type',
            field=models.CharField(choices=[('AI', 'AI用例生成'), ('AI_TEST', 'AI智能测试'), ('API', 'API测试'), ('UI', 'UI自动化'), ('APP', 'APP自动化')], max_length=10, verbose_name='模块类型'),
        ),
    ]
