# Generated by Django 6.0.2 on 2026-02-27 11:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待评审'), ('approved', '已通过'), ('rejected', '已拒绝'), ('abstained', '弃权')], default='pending', max_length=20, verbose_name='评审状态')),
                ('comment', models.TextField(blank=True, verbose_name='评审意见')),
                ('checklist_results', models.JSONField(blank=True, default=dict, verbose_name='检查清单结果')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='评审时间')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='分配时间')),
            ],
            options={
                'verbose_name': '评审分配',
                'verbose_name_plural': '评审分配',
                'db_table': 'review_assignments',
            },
        ),
        migrations.CreateModel(
            name='ReviewTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, verbose_name='模板描述')),
                ('checklist', models.JSONField(default=list, verbose_name='检查清单')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '评审模板',
                'verbose_name_plural': '评审模板',
                'db_table': 'review_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCaseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='评审标题')),
                ('description', models.TextField(blank=True, verbose_name='评审描述')),
                ('status', models.CharField(choices=[('pending', '待评审'), ('in_progress', '评审中'), ('approved', '已通过'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='评审状态')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '紧急')], default='medium', max_length=20, verbose_name='优先级')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='截止日期')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '测试用例评审',
                'verbose_name_plural': '测试用例评审',
                'db_table': 'testcase_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCaseReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('general', '整体意见'), ('testcase', '用例意见'), ('step', '步骤意见')], default='general', max_length=20, verbose_name='意见类型')),
                ('content', models.TextField(verbose_name='意见内容')),
                ('step_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='步骤序号')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='是否已解决')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '评审意见',
                'verbose_name_plural': '评审意见',
                'db_table': 'review_comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
