# Generated by Django 6.0.2 on 2026-02-27 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        ('reviews', '0001_initial'),
        ('testcases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewassignment',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评审人'),
        ),
        migrations.AddField(
            model_name='reviewtemplate',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='reviewtemplate',
            name='default_reviewers',
            field=models.ManyToManyField(blank=True, related_name='template_reviews', to=settings.AUTH_USER_MODEL, verbose_name='默认评审人'),
        ),
        migrations.AddField(
            model_name='reviewtemplate',
            name='project',
            field=models.ManyToManyField(related_name='review_templates', to='projects.project', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='testcasereview',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reviews', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='testcasereview',
            name='projects',
            field=models.ManyToManyField(related_name='reviews', to='projects.project', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='testcasereview',
            name='reviewers',
            field=models.ManyToManyField(related_name='assigned_reviews', through='reviews.ReviewAssignment', to=settings.AUTH_USER_MODEL, verbose_name='评审人员'),
        ),
        migrations.AddField(
            model_name='testcasereview',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_reviews', to='reviews.reviewtemplate', verbose_name='使用的模板'),
        ),
        migrations.AddField(
            model_name='testcasereview',
            name='testcases',
            field=models.ManyToManyField(related_name='reviews', to='testcases.testcase', verbose_name='评审用例'),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.testcasereview', verbose_name='评审'),
        ),
        migrations.AddField(
            model_name='testcasereviewcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论者'),
        ),
        migrations.AddField(
            model_name='testcasereviewcomment',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.testcasereview', verbose_name='评审'),
        ),
        migrations.AddField(
            model_name='testcasereviewcomment',
            name='testcase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_comments', to='testcases.testcase', verbose_name='相关用例'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewassignment',
            unique_together={('review', 'reviewer')},
        ),
    ]
