# Generated by Django 6.0.2 on 2026-02-27 11:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, verbose_name='模板描述')),
                ('template_config', models.JSONField(default=dict, verbose_name='模板配置')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '报告模板',
                'verbose_name_plural': '报告模板',
                'db_table': 'report_templates',
            },
        ),
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='报告名称')),
                ('report_type', models.CharField(choices=[('execution', '执行报告'), ('summary', '汇总报告'), ('trend', '趋势报告')], default='execution', max_length=20, verbose_name='报告类型')),
                ('summary', models.JSONField(default=dict, verbose_name='报告摘要')),
                ('content', models.JSONField(default=dict, verbose_name='报告内容')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '测试报告',
                'verbose_name_plural': '测试报告',
                'db_table': 'test_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
