# Generated by Django 5.1.4 on 2026-03-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testreport',
            name='status',
            field=models.CharField(choices=[('running', '执行中'), ('completed', '已完成'), ('failed', '执行失败')], default='running', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='testreport',
            name='total_cases',
            field=models.IntegerField(default=0, verbose_name='总用例数'),
        ),
        migrations.AddField(
            model_name='testreport',
            name='passed_cases',
            field=models.IntegerField(default=0, verbose_name='通过数'),
        ),
        migrations.AddField(
            model_name='testreport',
            name='failed_cases',
            field=models.IntegerField(default=0, verbose_name='失败数'),
        ),
        migrations.AddField(
            model_name='testreport',
            name='skipped_cases',
            field=models.IntegerField(default=0, verbose_name='跳过数'),
        ),
        migrations.AddField(
            model_name='testreport',
            name='error_cases',
            field=models.IntegerField(default=0, verbose_name='错误数'),
        ),
        migrations.AddField(
            model_name='testreport',
            name='duration',
            field=models.FloatField(default=0, verbose_name='执行时长(秒)'),
        ),
        migrations.AddField(
            model_name='testreport',
            name='html_content',
            field=models.TextField(blank=True, verbose_name='HTML报告内容'),
        ),
        migrations.AddField(
            model_name='testreport',
            name='allure_report_url',
            field=models.URLField(blank=True, default='', verbose_name='Allure报告链接'),
        ),
        migrations.AddField(
            model_name='testreport',
            name='environment_info',
            field=models.JSONField(blank=True, default=dict, verbose_name='环境信息'),
        ),
        migrations.AddField(
            model_name='testreport',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AddField(
            model_name='testreport',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='testreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='generated_by',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='generated_reports', to='users.user', verbose_name='生成者'),
        ),
    ]
