export default {
  // Sidebar
  newChat: 'New Chat',
  historyChat: 'History',
  user: 'User',
  goHome: 'Go Home',
  logout: 'Logout',
  deleteSessionConfirm: 'Are you sure to delete this session?',
  logoutConfirm: 'Are you sure you want to logout?',
  logoutTitle: 'Confirm',
  confirm: 'Confirm',
  cancel: 'Cancel',
  loggedOut: 'Logged out successfully',

  // Welcome Page
  title: 'AI Reviewer',
  subtitle: "I'm your professional testing assistant. How can I help you?",
  inputPlaceholder: 'Enter your question, press Enter to send...',
  chatInputPlaceholder: 'Enter message...',

  // Suggestions
  suggestions: {
    apiTest: 'API Test Cases',
    apiTestQuestion: 'How to design test cases for login API?',
    performancePlan: 'Performance Test Plan',
    performancePlanQuestion: 'Help me generate a performance test plan template',
    testTheory: 'Testing Theory',
    testTheoryQuestion: 'Explain the boundary value analysis method',
    automationDebug: 'Automation Debug',
    automationDebugQuestion: 'What to do when Python Selenium fails to locate elements?'
  },

  // Chat
  thinking: 'Thinking...',
  aiDisclaimer: 'Content generated by AI, please verify carefully',

  // Messages
  messages: {
    loadMessageFailed: 'Failed to load messages',
    sessionDeleted: 'Session deleted',
    deleteSessionFailed: 'Failed to delete session',
    sendFailed: 'Failed to send, please try again',
    loadHistoryFailed: 'Failed to load history'
  }
}
