# Generated by Django 6.0.2 on 2026-02-27 11:46

import apps.requirement_analysis.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('model_type', models.CharField(choices=[('deepseek', 'DeepSeek'), ('qwen', '通义千问'), ('siliconflow', '硅基流动'), ('zhipu', '智谱'), ('other', '其他')], max_length=20, verbose_name='模型类型')),
                ('role', models.CharField(choices=[('writer', '测试用例编写专家'), ('reviewer', '测试评审专家'), ('browser_use_text', 'Browser Use - 文本模式')], max_length=20, verbose_name='角色')),
                ('api_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='API Key')),
                ('base_url', models.URLField(verbose_name='API Base URL')),
                ('model_name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('max_tokens', models.IntegerField(default=4096, verbose_name='最大Token数')),
                ('temperature', models.FloatField(default=0.7, verbose_name='温度参数')),
                ('top_p', models.FloatField(default=0.9, verbose_name='Top P参数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI模型配置',
                'verbose_name_plural': 'AI模型配置',
                'db_table': 'ai_model_config',
            },
        ),
        migrations.CreateModel(
            name='AnalysisTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100, unique=True, verbose_name='任务ID')),
                ('task_type', models.CharField(choices=[('requirement_analysis', '需求分析'), ('testcase_generation', '测试用例生成'), ('testcase_review', '测试用例评审')], max_length=30, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='进度百分比')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='任务结果')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '分析任务',
                'verbose_name_plural': '分析任务',
                'db_table': 'analysis_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_id', models.CharField(max_length=50, verbose_name='需求编号')),
                ('requirement_name', models.CharField(max_length=200, verbose_name='需求名称')),
                ('requirement_type', models.CharField(choices=[('functional', '功能需求'), ('performance', '性能需求'), ('security', '安全需求'), ('usability', '可用性需求'), ('interface', '接口需求'), ('other', '其他需求')], max_length=20, verbose_name='需求类型')),
                ('module', models.CharField(max_length=100, verbose_name='所属模块')),
                ('requirement_level', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], max_length=10, verbose_name='需求级别')),
                ('reviewer', models.CharField(default='admin', max_length=50, verbose_name='评审人')),
                ('estimated_hours', models.PositiveIntegerField(default=8, verbose_name='预计工时')),
                ('description', models.TextField(verbose_name='需求描述')),
                ('acceptance_criteria', models.TextField(verbose_name='验收标准')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '业务需求',
                'verbose_name_plural': '业务需求',
                'db_table': 'business_requirements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=50, verbose_name='用例编号')),
                ('title', models.CharField(max_length=300, verbose_name='用例标题')),
                ('priority', models.CharField(choices=[('P0', '最高优先级'), ('P1', '高优先级'), ('P2', '中优先级'), ('P3', '低优先级')], max_length=5, verbose_name='优先级')),
                ('precondition', models.TextField(verbose_name='前置条件')),
                ('test_steps', models.TextField(verbose_name='测试步骤')),
                ('expected_result', models.TextField(verbose_name='预期结果')),
                ('status', models.CharField(choices=[('generated', '已生成'), ('reviewing', '评审中'), ('reviewed', '已评审'), ('approved', '已批准'), ('rejected', '已拒绝'), ('adopted', '已采纳'), ('discarded', '已弃用')], default='generated', max_length=20, verbose_name='状态')),
                ('generated_by_ai', models.CharField(default='AI-A', max_length=50, verbose_name='生成AI模型')),
                ('reviewed_by_ai', models.CharField(blank=True, max_length=50, null=True, verbose_name='评审AI模型')),
                ('review_comments', models.TextField(blank=True, verbose_name='评审意见')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '生成的测试用例',
                'verbose_name_plural': '生成的测试用例',
                'db_table': 'generated_test_cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='默认生成配置', max_length=100, verbose_name='配置名称')),
                ('default_output_mode', models.CharField(choices=[('stream', '实时流式输出'), ('complete', '完整输出')], default='stream', help_text='测试用例生成的默认输出方式', max_length=10, verbose_name='默认输出模式')),
                ('enable_auto_review', models.BooleanField(default=True, help_text='生成完成后自动进行AI评审，并根据评审意见改进测试用例', verbose_name='启用AI评审和改进')),
                ('review_timeout', models.IntegerField(default=120, help_text='AI评审和改进的最大等待时间（总时长）', verbose_name='评审和改进超时时间（秒）')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '生成行为配置',
                'verbose_name_plural': '生成行为配置',
                'db_table': 'generation_config',
            },
        ),
        migrations.CreateModel(
            name='PromptConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('prompt_type', models.CharField(choices=[('writer', '用例编写提示词'), ('reviewer', '用例评审提示词')], max_length=20, verbose_name='提示词类型')),
                ('content', models.TextField(verbose_name='提示词内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '提示词配置',
                'verbose_name_plural': '提示词配置',
                'db_table': 'prompt_config',
            },
        ),
        migrations.CreateModel(
            name='RequirementAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_report', models.TextField(blank=True, verbose_name='分析报告')),
                ('requirements_count', models.PositiveIntegerField(default=0, verbose_name='需求数量')),
                ('analysis_time', models.FloatField(blank=True, null=True, verbose_name='分析耗时(秒)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '需求分析',
                'verbose_name_plural': '需求分析',
                'db_table': 'requirement_analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequirementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文档标题')),
                ('file', models.FileField(storage=apps.requirement_analysis.models.RequirementDocsStorage(), upload_to=apps.requirement_analysis.models.requirement_docs_upload_path, verbose_name='文档文件')),
                ('document_type', models.CharField(choices=[('pdf', 'PDF文档'), ('docx', 'Word文档'), ('txt', '文本文档'), ('md', 'Markdown文档')], max_length=10, verbose_name='文档类型')),
                ('status', models.CharField(choices=[('uploaded', '已上传'), ('analyzing', '分析中'), ('analyzed', '分析完成'), ('failed', '分析失败')], default='uploaded', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='文件大小(bytes)')),
                ('extracted_text', models.TextField(blank=True, verbose_name='提取的文本内容')),
            ],
            options={
                'verbose_name': '需求文档',
                'verbose_name_plural': '需求文档',
                'db_table': 'requirement_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCaseGenerationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=50, unique=True, verbose_name='任务ID')),
                ('title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('requirement_text', models.TextField(verbose_name='需求描述')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('generating', '生成中'), ('reviewing', '评审中'), ('revising', '改进中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度百分比')),
                ('output_mode', models.CharField(choices=[('stream', '实时流式输出'), ('complete', '完整输出')], default='stream', max_length=10, verbose_name='输出模式')),
                ('stream_buffer', models.TextField(blank=True, verbose_name='流式输出缓冲区')),
                ('stream_position', models.IntegerField(default=0, verbose_name='流式输出位置')),
                ('last_stream_update', models.DateTimeField(blank=True, null=True, verbose_name='最后流式更新时间')),
                ('generated_test_cases', models.TextField(blank=True, verbose_name='生成的测试用例')),
                ('review_feedback', models.TextField(blank=True, verbose_name='评审反馈')),
                ('final_test_cases', models.TextField(blank=True, verbose_name='最终测试用例')),
                ('generation_log', models.TextField(blank=True, verbose_name='生成日志')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('is_saved_to_records', models.BooleanField(default=False, verbose_name='是否已保存到记录')),
                ('saved_at', models.DateTimeField(blank=True, null=True, verbose_name='保存到记录时间')),
            ],
            options={
                'verbose_name': '测试用例生成任务',
                'verbose_name_plural': '测试用例生成任务',
                'db_table': 'testcase_generation_task',
                'ordering': ['-created_at'],
            },
        ),
    ]
