# Generated by Django 6.0.1 on 2026-02-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementdocument',
            name='file',
            field=models.FileField(upload_to='requirement_docs/%Y/%m/', verbose_name='文档文件'),
        ),
    ]
