# Generated by Django 6.0.2 on 2026-02-27 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        ('requirement_analysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelconfig',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='businessrequirement',
            name='parent_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requirement_analysis.businessrequirement', verbose_name='父级需求'),
        ),
        migrations.AddField(
            model_name='generatedtestcase',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='requirement_analysis.businessrequirement', verbose_name='关联需求'),
        ),
        migrations.AddField(
            model_name='promptconfig',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='businessrequirement',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='requirement_analysis.requirementanalysis', verbose_name='关联分析'),
        ),
        migrations.AddField(
            model_name='requirementdocument',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirement_documents', to='projects.project', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='requirementdocument',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
        migrations.AddField(
            model_name='requirementanalysis',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='requirement_analysis.requirementdocument', verbose_name='关联文档'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='requirement_analysis.requirementdocument', verbose_name='关联文档'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_tasks', to='projects.project', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='reviewer_model_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_tasks', to='requirement_analysis.aimodelconfig', verbose_name='评审模型配置'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='reviewer_prompt_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_tasks', to='requirement_analysis.promptconfig', verbose_name='评审提示词配置'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='writer_model_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writer_tasks', to='requirement_analysis.aimodelconfig', verbose_name='编写模型配置'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='writer_prompt_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writer_tasks', to='requirement_analysis.promptconfig', verbose_name='编写提示词配置'),
        ),
        migrations.AlterUniqueTogether(
            name='generatedtestcase',
            unique_together={('requirement', 'case_id')},
        ),
        migrations.AlterUniqueTogether(
            name='businessrequirement',
            unique_together={('analysis', 'requirement_id')},
        ),
    ]
