# Generated by Django 6.0.1 on 2026-02-24 10:19

import apps.requirement_analysis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0002_alter_requirementdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementdocument',
            name='file',
            field=models.FileField(storage=apps.requirement_analysis.models.RequirementDocsStorage(), upload_to=apps.requirement_analysis.models.requirement_docs_upload_path, verbose_name='文档文件'),
        ),
    ]
