# Generated by Django 6.0.2 on 2026-03-05 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0002_initial'),
        ('requirement_analysis', '0003_alter_requirementdocument_file'),
    ]

    operations = [
    ]
