# Generated by Django 6.0.2 on 2026-04-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0004_merge_20260305_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelconfig',
            name='config_type',
            field=models.CharField(choices=[('llm', '大语言模型'), ('ocr', 'OCR 识别')], default='llm', max_length=10, verbose_name='配置类型'),
        ),
        migrations.AddField(
            model_name='aimodelconfig',
            name='ocr_language',
            field=models.CharField(default='chi_sim+eng', help_text='Tesseract: chi_sim(中文), eng(英文), chi_sim+eng(中英文)', max_length=20, verbose_name='OCR 识别语言'),
        ),
        migrations.AddField(
            model_name='aimodelconfig',
            name='ocr_provider',
            field=models.CharField(blank=True, choices=[('tesseract', 'Tesseract OCR'), ('ppocr', 'PP-OCRv5'), ('openai', 'OpenAI GPT-4V'), ('zhipu', '智谱 GLM-4V'), ('baidu', '百度 AI OCR'), ('tencent', '腾讯 OCR'), ('aliyun', '阿里云 OCR'), ('custom', '自定义 OCR')], max_length=20, null=True, verbose_name='OCR 服务提供商'),
        ),
        migrations.AddField(
            model_name='aimodelconfig',
            name='ocr_use_gpu',
            field=models.BooleanField(default=False, verbose_name='OCR 使用 GPU'),
        ),
        migrations.AlterField(
            model_name='aimodelconfig',
            name='base_url',
            field=models.URLField(blank=True, null=True, verbose_name='API Base URL'),
        ),
        migrations.AlterField(
            model_name='aimodelconfig',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='模型名称'),
        ),
        migrations.AlterField(
            model_name='aimodelconfig',
            name='model_type',
            field=models.CharField(blank=True, choices=[('deepseek', 'DeepSeek'), ('qwen', '通义千问'), ('siliconflow', '硅基流动'), ('zhipu', '智谱'), ('other', '其他')], max_length=20, null=True, verbose_name='模型类型'),
        ),
        migrations.AlterField(
            model_name='aimodelconfig',
            name='role',
            field=models.CharField(choices=[('writer', '测试用例编写专家'), ('reviewer', '测试评审专家'), ('browser_use_text', 'Browser Use - 文本模式'), ('ocr', 'OCR 文字识别')], max_length=20, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='requirementdocument',
            name='document_type',
            field=models.CharField(choices=[('auto', '自动识别'), ('pdf', 'PDF文档'), ('docx', 'Word文档'), ('txt', '文本文档'), ('md', 'Markdown文档')], max_length=10, verbose_name='文档类型'),
        ),
    ]
