# Generated by Django 6.0.2 on 2026-04-08 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('provider', models.CharField(choices=[('tesseract', 'Tesseract OCR'), ('ppocr', 'PP-OCRv5'), ('openai', 'OpenAI GPT-4V'), ('zhipu', '智谱 GLM-4V'), ('baidu', '百度 AI OCR'), ('tencent', '腾讯 OCR'), ('aliyun', '阿里云 OCR'), ('custom', '自定义 OCR')], max_length=20, verbose_name='OCR 服务提供商')),
                ('api_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='API Key')),
                ('base_url', models.URLField(blank=True, null=True, verbose_name='API Base URL')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='模型名称')),
                ('language', models.CharField(default='chi_sim+eng', help_text='Tesseract: chi_sim(中文), eng(英文), chi_sim+eng(中英文)', max_length=20, verbose_name='识别语言')),
                ('use_gpu', models.BooleanField(default=False, verbose_name='使用 GPU')),
                ('min_confidence', models.FloatField(default=0.3, verbose_name='最小置信度')),
                ('extra_config', models.JSONField(blank=True, default=dict, verbose_name='额外配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': 'OCR 配置',
                'verbose_name_plural': 'OCR 配置',
                'db_table': 'ocr_config',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OCRTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=50, unique=True, verbose_name='任务ID')),
                ('image_path', models.CharField(max_length=500, verbose_name='图片路径')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('result_text', models.TextField(blank=True, verbose_name='识别结果')),
                ('result_data', models.JSONField(blank=True, null=True, verbose_name='详细结果')),
                ('confidence', models.FloatField(blank=True, null=True, verbose_name='置信度')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='处理耗时(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ocr_service.ocrconfig', verbose_name='OCR 配置')),
            ],
            options={
                'verbose_name': 'OCR 任务',
                'verbose_name_plural': 'OCR 任务',
                'db_table': 'ocr_task',
                'ordering': ['-created_at'],
            },
        ),
    ]
