# Generated by Django 6.0.2 on 2026-04-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_service', '0002_remove_ppocr_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrconfig',
            name='provider',
            field=models.CharField(choices=[('tesseract', 'Tesseract OCR'), ('openai', 'OpenAI GPT-4V'), ('zhipu', '智谱 GLM-4V'), ('siliconflow', '硅基流动'), ('baidu', '百度 AI OCR'), ('tencent', '腾讯 OCR'), ('aliyun', '阿里云 OCR'), ('custom', '自定义 OCR')], max_length=20, verbose_name='OCR 服务提供商'),
        ),
    ]
