# Generated by Django 6.0.2 on 2026-04-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_tools', '0002_category_and_directories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opsenvironment',
            name='image_host',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='图片主机'),
        ),
        migrations.AlterField(
            model_name='opsenvironment',
            name='mongo_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='MongoDB 配置'),
        ),
    ]
